### ISSUE TITLE
Prior Art

### ISSUE THREAD

**Issue by kat-co** [storozhukBM/verifier#7]
Hey, looks like we had the same idea :) Here's some prior art if it's helpful:

https://github.com/kat-co/vala
https://katherine.cox-buday.com/blog/2014/07/31/an-argument-for-parameter-validation/

**Comment by storozhukBM** [comment]
Hi Katherine,
Thank you for this links and materials. Vala looks really neat 👍 and API is fluid and flexible.
As for me, I prefer old school imperative style, like [here](https://commons.apache.org/proper/commons-lang/javadocs/api-2.4/org/apache/commons/lang/Validate.html).
But it is great that Go users have whole variety of options to choose from.
I'll create a section in readme, with links to other helpful libraries from the similar field.
