### ISSUE TITLE
multiple checks in one line?

### ISSUE THREAD

**Issue by initbar** [storozhukBM/verifier#9]
Using `verifier`, is it possible write in a pattern such as below to test multiple parameters at once?

```go
package main

import (
	"github.com/storozhukBM/verifier"
)

func main() {
	test("", "")
}

func test(a, b string) {
	verify := verifier.New()
	verify.That(a, b != "", "a or b cannot be empty strings.")
}
```

**Comment by storozhukBM** [comment]
I'd recommend you to check different statements on separate lines, to provide specific error messages...
But you can always use some boolean algebra:
```go
verify.That(a != "" && b != "", "a or b cannot be empty strings.")
```

**Comment by initbar** [comment]
That's true, thank you!
